[package]

name = "amp"
version = "0.5.0"
authors = ["Jordan MacDonald <jordan@wastedintelligence.com>"]
description = "A complete text editor for your terminal."
homepage = "https://amp.rs"
repository = "https://github.com/jmacdonald/amp"
documentation = "https://amp.rs/docs"
readme = "README.md"
license-file = "LICENSE"
keywords = ["text", "editor", "terminal", "modal"]

[build-dependencies]
syntex_syntax = "0.58.1"

[dependencies]
app_dirs = "1.2.1"
scribe = "0.7.0"
pad = "0.1.4"
bloodhound = "0.5.4"
luthor = "0.1.7"
git2 = "0.6"
fragment = "0.3.1"
regex = "^0.1"
libc = "0.2.4"
syntect = "2.1.0"
rustbox = "0.11.0"
termion = "1.5.1"
error-chain = "0.12.0"
unicode-segmentation = "1.0.1"
clipboard = "0.4.4"
yaml-rust = "0.3.5"
smallvec = "0.4.3"

[patch.crates-io]
termbox-sys = { git="https://github.com/jmacdonald/termbox-sys" }

[dev-dependencies]
criterion = "0.2.0"

[features]
bench = []

[[bench]]
name = "draw_buffer"
path = "benches/view/draw_buffer.rs"
harness = false
